/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Modelo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import javax.imageio.ImageIO;

/**
 *
 * @author user
 */
public class Lienzo extends javax.swing.JPanel {
    
     /**
     * Creates new form PanelFiguras
     */
    public Lienzo() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Atributos
    private Trazo trazoActual;
    private Figura figuraActual;
    private Color colorActual = Color.BLACK; 
    private Color colorAnterior = Color.BLACK;
    private int grosorActual = 2; 
    private String tipo;
    private boolean trazoActivo = true; 
    private boolean figuraActiva = false; 
    private final ArrayList<Dibujo> dibujos = new ArrayList<>();
    private final ArrayList<Dibujo> dibujosEliminados = new ArrayList();
    
    // Metodos
    
    public boolean guardarImagen(String name,String type) {
        BufferedImage image = new BufferedImage(this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = image.createGraphics();
        paint(g2d);
        try {
            ImageIO.write(image, type, new File(name + "." + type));
            return true;
        } catch (IOException e) {
            return false;
        }
    }
    
    public void limpiarLienzo() {
        dibujos.clear();
        repaint();
    }
    
    public void deshacer() {
        
        try {
            
            dibujosEliminados.add(dibujos.get(dibujos.size() - 1));
            dibujos.removeLast();
            repaint();
            
        } catch (NoSuchElementException | IndexOutOfBoundsException e) {}
        
    }
    
    public void rehacer() {
        
        try {
            
            dibujos.add(dibujosEliminados.get(dibujosEliminados.size() - 1));
            dibujosEliminados.removeLast();
            repaint();
            
        } catch (NoSuchElementException | IndexOutOfBoundsException e) {}
        
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    public void setEstadoActual(boolean trazoActivo, boolean figuraActiva, boolean borradorActivo) {
        this.figuraActiva = figuraActiva;
        this.trazoActivo = trazoActivo;

        if (borradorActivo) {
            colorAnterior = colorActual;
            colorActual = Color.WHITE;
        } else {
            colorActual = colorAnterior;
        }
        repaint();
    }
    
    public void setColorActual(Color color) {
        this.colorActual = color;
        colorAnterior = color;
        repaint();
    }
    
    public void setGrosorActual(int grosor) {
        this.grosorActual = grosor; 
        if (trazoActual != null) {
            trazoActual.setGrosor(grosor);
        }
        if (figuraActual != null) {
            figuraActual.setGrosor(grosor);
        }
    }  
    
    // Sobreescribir el metodo abstracto
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        for (Dibujo dibujo : dibujos) {
            dibujo.dibujar(g2d);
        }

        if (trazoActivo && trazoActual != null) {
            trazoActual.dibujar(g2d);
        }

        if (figuraActiva && figuraActual != null) {
            figuraActual.dibujar(g2d);
        }
    }
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       
        // Trazo
        if (trazoActivo && trazoActual != null) {
            trazoActual.addPoint(new Point(evt.getX(), evt.getY()));
            repaint();
        }

        // Figura
        if (figuraActiva && figuraActual != null) {
            Point inicio = figuraActual.getInicio();
            figuraActual.crearFigura(inicio, new Point(evt.getX(), evt.getY()), tipo);  
            repaint();
        }
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Trazo
        if (trazoActivo) {
            trazoActual = new Trazo(colorActual, grosorActual);
            trazoActual.addPoint(new Point(evt.getX(), evt.getY()));
        }

        // Figura
        if (figuraActiva) {
            figuraActual = new Figura(colorActual, grosorActual, new Point(evt.getX(), evt.getY()), new Point(evt.getX(), evt.getY()), tipo); 
        }
        repaint();
    }//GEN-LAST:event_formMousePressed
    
    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
        // Trazo
        if (trazoActivo && trazoActual != null) {
            trazoActual.addPoint(new Point(evt.getX(), evt.getY()));
            dibujos.add(trazoActual);
            trazoActual = null;
            repaint();
        }
        
        // Figura
        if (figuraActiva && figuraActual != null) {
            Point inicio = figuraActual.getInicio();
            figuraActual.crearFigura(inicio, new Point(evt.getX(), evt.getY()), tipo); 
            dibujos.add(figuraActual);
            figuraActual = null;
            repaint();
        }
        
    }//GEN-LAST:event_formMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
