/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Inicio extends javax.swing.JFrame {
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents(); 
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        lienzo = new Modelo.Lienzo();
        herramientas = new javax.swing.JPanel();
        lapiz = new javax.swing.JButton();
        borrador = new javax.swing.JButton();
        botonNegro = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();
        botonColorVerde = new javax.swing.JButton();
        botonRojo = new javax.swing.JButton();
        deslizador = new javax.swing.JSlider();
        tamanoDePincel = new javax.swing.JLabel();
        botonInsertarRectangulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonInsertarCirculo = new javax.swing.JButton();
        btnColorAzul = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();
        btnDeshacer1 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        limpiarLienzo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AppDibujo");

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        lienzo.setBackground(new java.awt.Color(255, 255, 255));
        lienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        herramientas.setPreferredSize(new java.awt.Dimension(10, 10));

        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        lapiz.setAlignmentY(0.0F);
        lapiz.setMaximumSize(new java.awt.Dimension(10, 10));
        lapiz.setMinimumSize(new java.awt.Dimension(10, 10));
        lapiz.setPreferredSize(new java.awt.Dimension(30, 30));
        lapiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lapizMousePressed(evt);
            }
        });

        borrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrador.png"))); // NOI18N
        borrador.setAlignmentY(0.0F);
        borrador.setMaximumSize(new java.awt.Dimension(10, 10));
        borrador.setMinimumSize(new java.awt.Dimension(10, 10));
        borrador.setPreferredSize(new java.awt.Dimension(30, 30));
        borrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borradorMousePressed(evt);
            }
        });

        botonNegro.setBackground(new java.awt.Color(0, 0, 0));
        botonNegro.setPreferredSize(new java.awt.Dimension(25, 25));
        botonNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonNegroMousePressed(evt);
            }
        });

        botonAmarillo.setBackground(new java.awt.Color(255, 255, 51));
        botonAmarillo.setPreferredSize(new java.awt.Dimension(25, 25));
        botonAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAmarilloMousePressed(evt);
            }
        });

        botonColorVerde.setBackground(new java.awt.Color(102, 255, 0));
        botonColorVerde.setPreferredSize(new java.awt.Dimension(25, 25));
        botonColorVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonColorVerdeMousePressed(evt);
            }
        });

        botonRojo.setBackground(new java.awt.Color(255, 0, 51));
        botonRojo.setPreferredSize(new java.awt.Dimension(25, 25));
        botonRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRojoMousePressed(evt);
            }
        });

        deslizador.setMajorTickSpacing(1);
        deslizador.setMinimum(1);
        deslizador.setSnapToTicks(true);
        deslizador.setValue(2);
        deslizador.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deslizadorStateChanged(evt);
            }
        });

        tamanoDePincel.setText(" 100");
        tamanoDePincel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tamanoDePincelPropertyChange(evt);
            }
        });

        botonInsertarRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuadrado.png"))); // NOI18N
        botonInsertarRectangulo.setPreferredSize(new java.awt.Dimension(30, 30));
        botonInsertarRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInsertarRectanguloMousePressed(evt);
            }
        });

        botonInsertarCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ovalo.png"))); // NOI18N
        botonInsertarCirculo.setPreferredSize(new java.awt.Dimension(30, 30));
        botonInsertarCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInsertarCirculoMousePressed(evt);
            }
        });

        btnColorAzul.setBackground(new java.awt.Color(0, 153, 255));
        btnColorAzul.setPreferredSize(new java.awt.Dimension(25, 25));
        btnColorAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnColorAzulMousePressed(evt);
            }
        });

        btnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/deshacer.png"))); // NOI18N
        btnDeshacer.setPreferredSize(new java.awt.Dimension(30, 30));
        btnDeshacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeshacerMousePressed(evt);
            }
        });

        btnDeshacer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rehacer.png"))); // NOI18N
        btnDeshacer1.setPreferredSize(new java.awt.Dimension(30, 30));
        btnDeshacer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeshacer1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout herramientasLayout = new javax.swing.GroupLayout(herramientas);
        herramientas.setLayout(herramientasLayout);
        herramientasLayout.setHorizontalGroup(
            herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(herramientasLayout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, herramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lapiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInsertarRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonInsertarCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeshacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeshacer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deslizador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamanoDePincel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonColorVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        herramientasLayout.setVerticalGroup(
            herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(herramientasLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lapiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(herramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(borrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonInsertarRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonInsertarCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeshacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deslizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonColorVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonNegro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnColorAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeshacer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tamanoDePincel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(88, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        archivo.setText("Archivo");

        abrir.setText("Abrir imagen");
        abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                abrirMousePressed(evt);
            }
        });
        archivo.add(abrir);

        guardar.setText("Guardar imagen");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarMousePressed(evt);
            }
        });
        archivo.add(guardar);

        limpiarLienzo.setText("Limpiar lienzo");
        limpiarLienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiarLienzoMousePressed(evt);
            }
        });
        archivo.add(limpiarLienzo);

        menu.add(archivo);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void tamanoDePincelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tamanoDePincelPropertyChange
        tamanoDePincel.setText(String.valueOf(deslizador.getValue()));
    }//GEN-LAST:event_tamanoDePincelPropertyChange

    private void deslizadorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deslizadorStateChanged
        lienzo.setGrosorActual(deslizador.getValue());
        tamanoDePincel.setText(String.valueOf(deslizador.getValue()));
    }//GEN-LAST:event_deslizadorStateChanged

    private void lapizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapizMousePressed
        lienzo.setEstadoActual(true, false, false);
    }//GEN-LAST:event_lapizMousePressed

    private void borradorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borradorMousePressed
        lienzo.setEstadoActual(true, false, true);
    }//GEN-LAST:event_borradorMousePressed

    private void botonInsertarRectanguloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarRectanguloMousePressed
        lienzo.setEstadoActual(false, true, false);
        lienzo.setTipo("Rectangulo");
    }//GEN-LAST:event_botonInsertarRectanguloMousePressed

    private void botonNegroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNegroMousePressed
        lienzo.setColorActual(Color.BLACK);
    }//GEN-LAST:event_botonNegroMousePressed

    private void botonColorVerdeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonColorVerdeMousePressed
        lienzo.setColorActual(Color.GREEN);
    }//GEN-LAST:event_botonColorVerdeMousePressed

    private void botonAmarilloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAmarilloMousePressed
        lienzo.setColorActual(Color.YELLOW);
    }//GEN-LAST:event_botonAmarilloMousePressed

    private void botonRojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRojoMousePressed
        lienzo.setColorActual(Color.RED);
    }//GEN-LAST:event_botonRojoMousePressed

    private void botonInsertarCirculoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInsertarCirculoMousePressed
        lienzo.setEstadoActual(false, true, false);
        lienzo.setTipo("Ovalo");
    }//GEN-LAST:event_botonInsertarCirculoMousePressed

    private void btnColorAzulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorAzulMousePressed
        lienzo.setColorActual(Color.BLUE);
    }//GEN-LAST:event_btnColorAzulMousePressed

    private void btnDeshacerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshacerMousePressed
        lienzo.deshacer();
    }//GEN-LAST:event_btnDeshacerMousePressed

    private void btnDeshacer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshacer1MousePressed
        lienzo.rehacer();
    }//GEN-LAST:event_btnDeshacer1MousePressed

    private void limpiarLienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarLienzoMousePressed
        lienzo.limpiarLienzo();
    }//GEN-LAST:event_limpiarLienzoMousePressed

    private void guardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMousePressed
        if (lienzo.guardarImagen("imagen", "png")) {
            String mensaje = "¡Imagen guardada correctamente!";
            JOptionPane.showMessageDialog(rootPane, mensaje);
        } else {
            String mensaje = "¡Error al guardar la imagen";
            JOptionPane.showMessageDialog(rootPane, mensaje);
        }
        
    }//GEN-LAST:event_guardarMousePressed

    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged

    }//GEN-LAST:event_lienzoMouseDragged

    private void abrirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMousePressed

    }//GEN-LAST:event_abrirMousePressed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton borrador;
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonColorVerde;
    private javax.swing.JButton botonInsertarCirculo;
    private javax.swing.JButton botonInsertarRectangulo;
    private javax.swing.JButton botonNegro;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton btnColorAzul;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JButton btnDeshacer1;
    private javax.swing.JSlider deslizador;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JPanel herramientas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lapiz;
    private Modelo.Lienzo lienzo;
    private javax.swing.JMenuItem limpiarLienzo;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel tamanoDePincel;
    // End of variables declaration//GEN-END:variables
}
